name: Black Code Formatter

on:
  workflow_run:
    workflows:
      - install dependencies chatminal
    types:
      - completed

jobs:
  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: python-dependencies
          path: ~/.cache/pip

      - name: Run Black
        run: |
          pip install black
          black --check .
