name: Flake8 Linting

on:
  workflow_run:
    workflows:
      - Main CI Workflow
    types:
      - completed

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: python-dependencies
          path: ~/.cache/pip

      - name: Run Flake8
        run: |
          python -m pip install flake8
          flake8 ./app/*.py
